defaults:
  - _self_
  - override hydra/job_logging: custom
  - override hydra/output: custom

hydra:
  job:
    name: .
    chdir: False

  # Configure Hydra's own output
  output_subdir: .hydra

  # Disable Hydra's own verbose output
  verbose: false

  # Don't print Hydra logs to console
  hydra_logging:
    root:
      level: INFO
      handlers: []

# LLM client configuration
llm:
  model: gpt-4o-mini
  temperature: 1.0

# MCTS configuration
mcts:
  iterations_per_function: 10
  max_depth: 10

# Paths configuration
paths:
  project_root: ${hydra:runtime.cwd}
  results_dir: ${paths.project_root}/results

problem:
  active: tsp
  base_path: ${paths.project_root}/problems

  tsp:
    name: Traveling Salesman Problem
    base_path: ${problem.base_path}/tsp
    eval_script: ${problem.tsp.base_path}/eval.py
    functions:
      - id: F1
        name: HeuristicImpl
        path: ${problem.tsp.base_path}/F1.py
        base_class: HeuristicStrategy
      - id: F2
        name: ProbabilityImpl
        path: ${problem.tsp.base_path}/F2.py
        base_class: ProbabilityStrategy
      - id: F3
        name: PheromoneImpl
        path: ${problem.tsp.base_path}/F3.py
        base_class: PheromoneStrategy

  cvrp:
    name: Capacitated Vehicle Routing Problem
    base_path: ${problem.base_path}/cvrp
