defaults:
  - _self_
  - override hydra/job_logging: custom
  - override hydra/output: custom

hydra:
  job:
    name: .
    chdir: False

  # Configure Hydra's own output
  output_subdir: .hydra

  # Disable Hydra's own verbose output
  verbose: false

  # Don't print Hydra logs to console
  hydra_logging:
    root:
      level: INFO
      handlers: []

# LLM client configuration
llm:
  model: gpt-4o-mini
  temperature: 1.0

# Paths configuration
paths:
  project_root: ${hydra:runtime.cwd}
  results_dir: ${paths:project_root}/results
